version: '3'
services:
  api:
    extends:
      file: docker-compose.api.yml
      service: api
    # profiles:
    # - backend
    depends_on:
      - rmq
  rmq:
    image: rabbitmq:3-management
    restart: always
    networks:
      - myNetwork
    # env_file:
    # - .env
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
  app:
    build:
      context: .
      dockerfile: ./apps/app/Dockerfile
    ports:
      - 3001:80
    networks:
      - myNetwork
    restart: always
    container_name: app

  converter:
    build:
      dockerfile: ./apps/converter/Dockerfile
      context: .
    container_name: converter
    networks:
      - myNetwork
    volumes:
      - ./.env:/opt/app/.env
    restart: always
    depends_on:
      - rmq

networks:
  myNetwork:
    driver: bridge
